# Generated by Django 2.0.5 on 2018-06-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessoresInteressados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrimeiroNome', models.TextField(max_length=200)),
                ('SegundoNome', models.TextField(max_length=200)),
            ],
        ),
    ]
