# Generated by Django 2.0.5 on 2018-06-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=200)),
                ('sobrenome', models.TextField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='professoresinteressados',
            old_name='PrimeiroNome',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='professoresinteressados',
            old_name='SegundoNome',
            new_name='sobrenome',
        ),
    ]
