# Generated by Django 2.0.5 on 2018-06-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20180607_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='professoresinteressados',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/professores_img'),
        ),
    ]
