# Generated by Django 2.0.5 on 2018-06-08 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20180608_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
