# Generated by Django 2.0.5 on 2018-06-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_professor_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professoresinteressados',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
