# Generated by Django 2.0.5 on 2018-06-11 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20180608_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='professor',
            name='disciplina',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='index.Disciplina'),
            preserve_default=False,
        ),
    ]
