# Generated by Django 2.0.5 on 2018-06-11 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20180611_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professoresinteressados',
            name='disciplina',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='index.Disciplina'),
            preserve_default=False,
        ),
    ]
