# Generated by Django 2.0.5 on 2018-12-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_aulas'),
    ]

    operations = [
        migrations.AddField(
            model_name='aulas',
            name='nome',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aulas',
            name='titulo',
            field=models.TextField(max_length=200),
        ),
    ]
