# Generated by Django 2.0.5 on 2019-01-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20181218_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='professoresinteressados',
            name='aprovacao',
            field=models.BooleanField(default=False),
        ),
    ]
