# Generated by Django 2.0.5 on 2019-01-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_disciplina_aprovacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='aprovacao',
            field=models.BooleanField(default=True),
        ),
    ]
