# Generated by Django 2.0.5 on 2019-01-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_auto_20190110_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='aprovacao',
            field=models.BooleanField(default=False),
        ),
    ]
