# Generated by Django 2.0.5 on 2019-01-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_auto_20190110_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aulas',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='aulas',
            name='titulo',
        ),
        migrations.AddField(
            model_name='aulas',
            name='conteudo',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aulas',
            name='dia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aulas',
            name='disciplina',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aulas',
            name='duracao',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aulas',
            name='horario',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
