# Generated by Django 2.0.5 on 2019-01-11 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_auto_20190111_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='aulas',
            name='Professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='index.ProfessoresInteressados'),
        ),
    ]
